# Generated by Django 3.1.6 on 2021-07-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210701_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
