# Generated by Django 3.1.6 on 2021-07-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
